/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthenticatedGuichetRouteImport } from './routes/_authenticated/guichet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuichetRoute = AuthenticatedGuichetRouteImport.update({
  id: '/guichet',
  path: '/guichet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/guichet': typeof AuthenticatedGuichetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/guichet': typeof AuthenticatedGuichetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/espace': typeof AuthenticatedEspaceRoute
  '/_authenticated/guichet': typeof AuthenticatedGuichetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reinitialiser-mot-de-passe'
    | '/admin'
    | '/espace'
    | '/guichet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reinitialiser-mot-de-passe'
    | '/admin'
    | '/espace'
    | '/guichet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reinitialiser-mot-de-passe'
    | '/_authenticated/admin'
    | '/_authenticated/espace'
    | '/_authenticated/guichet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guichet': {
      id: '/_authenticated/guichet'
      path: '/guichet'
      fullPath: '/guichet'
      preLoaderRoute: typeof AuthenticatedGuichetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRoute
  AuthenticatedGuichetRoute: typeof AuthenticatedGuichetRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEspaceRoute: AuthenticatedEspaceRoute,
  AuthenticatedGuichetRoute: AuthenticatedGuichetRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
