/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedEspaceRouteRouteImport } from './routes/_authenticated/espace/route'
import { Route as AuthenticatedGuichetRouteRouteImport } from './routes/_authenticated/guichet/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin/agents'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminGuichetsRouteImport } from './routes/_authenticated/admin/guichets'
import { Route as AuthenticatedAdminProfilRouteImport } from './routes/_authenticated/admin/profil'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace/index'
import { Route as AuthenticatedEspaceFacturesRouteImport } from './routes/_authenticated/espace/factures'
import { Route as AuthenticatedEspacePayerFactureRouteImport } from './routes/_authenticated/espace/payer-facture'
import { Route as AuthenticatedEspaceProfilRouteImport } from './routes/_authenticated/espace/profil'
import { Route as AuthenticatedEspaceVerifierStatutRouteImport } from './routes/_authenticated/espace/verifier-statut'
import { Route as AuthenticatedGuichetIndexRouteImport } from './routes/_authenticated/guichet/index'
import { Route as AuthenticatedGuichetClientsRouteImport } from './routes/_authenticated/guichet/clients'
import { Route as AuthenticatedGuichetProfilRouteImport } from './routes/_authenticated/guichet/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceRouteRoute =
  AuthenticatedEspaceRouteRouteImport.update({
    id: '/espace',
    path: '/espace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuichetRouteRoute =
  AuthenticatedGuichetRouteRouteImport.update({
    id: '/guichet',
    path: '/guichet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGuichetsRoute =
  AuthenticatedAdminGuichetsRouteImport.update({
    id: '/guichets',
    path: '/guichets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProfilRoute =
  AuthenticatedAdminProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEspaceRouteRoute,
  } as any)
const AuthenticatedEspaceFacturesRoute =
  AuthenticatedEspaceFacturesRouteImport.update({
    id: '/factures',
    path: '/factures',
    getParentRoute: () => AuthenticatedEspaceRouteRoute,
  } as any)
const AuthenticatedEspacePayerFactureRoute =
  AuthenticatedEspacePayerFactureRouteImport.update({
    id: '/payer-facture',
    path: '/payer-facture',
    getParentRoute: () => AuthenticatedEspaceRouteRoute,
  } as any)
const AuthenticatedEspaceProfilRoute =
  AuthenticatedEspaceProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedEspaceRouteRoute,
  } as any)
const AuthenticatedEspaceVerifierStatutRoute =
  AuthenticatedEspaceVerifierStatutRouteImport.update({
    id: '/verifier-statut',
    path: '/verifier-statut',
    getParentRoute: () => AuthenticatedEspaceRouteRoute,
  } as any)
const AuthenticatedGuichetIndexRoute =
  AuthenticatedGuichetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGuichetRouteRoute,
  } as any)
const AuthenticatedGuichetClientsRoute =
  AuthenticatedGuichetClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedGuichetRouteRoute,
  } as any)
const AuthenticatedGuichetProfilRoute =
  AuthenticatedGuichetProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedGuichetRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/espace': typeof AuthenticatedEspaceRouteRouteWithChildren
  '/guichet': typeof AuthenticatedGuichetRouteRouteWithChildren
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/guichets': typeof AuthenticatedAdminGuichetsRoute
  '/admin/profil': typeof AuthenticatedAdminProfilRoute
  '/espace/factures': typeof AuthenticatedEspaceFacturesRoute
  '/espace/payer-facture': typeof AuthenticatedEspacePayerFactureRoute
  '/espace/profil': typeof AuthenticatedEspaceProfilRoute
  '/espace/verifier-statut': typeof AuthenticatedEspaceVerifierStatutRoute
  '/guichet/clients': typeof AuthenticatedGuichetClientsRoute
  '/guichet/profil': typeof AuthenticatedGuichetProfilRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/guichet/': typeof AuthenticatedGuichetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/guichets': typeof AuthenticatedAdminGuichetsRoute
  '/admin/profil': typeof AuthenticatedAdminProfilRoute
  '/espace/factures': typeof AuthenticatedEspaceFacturesRoute
  '/espace/payer-facture': typeof AuthenticatedEspacePayerFactureRoute
  '/espace/profil': typeof AuthenticatedEspaceProfilRoute
  '/espace/verifier-statut': typeof AuthenticatedEspaceVerifierStatutRoute
  '/guichet/clients': typeof AuthenticatedGuichetClientsRoute
  '/guichet/profil': typeof AuthenticatedGuichetProfilRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/guichet': typeof AuthenticatedGuichetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/espace': typeof AuthenticatedEspaceRouteRouteWithChildren
  '/_authenticated/guichet': typeof AuthenticatedGuichetRouteRouteWithChildren
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/guichets': typeof AuthenticatedAdminGuichetsRoute
  '/_authenticated/admin/profil': typeof AuthenticatedAdminProfilRoute
  '/_authenticated/espace/factures': typeof AuthenticatedEspaceFacturesRoute
  '/_authenticated/espace/payer-facture': typeof AuthenticatedEspacePayerFactureRoute
  '/_authenticated/espace/profil': typeof AuthenticatedEspaceProfilRoute
  '/_authenticated/espace/verifier-statut': typeof AuthenticatedEspaceVerifierStatutRoute
  '/_authenticated/guichet/clients': typeof AuthenticatedGuichetClientsRoute
  '/_authenticated/guichet/profil': typeof AuthenticatedGuichetProfilRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/guichet/': typeof AuthenticatedGuichetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reinitialiser-mot-de-passe'
    | '/admin'
    | '/espace'
    | '/guichet'
    | '/admin/agents'
    | '/admin/clients'
    | '/admin/guichets'
    | '/admin/profil'
    | '/espace/factures'
    | '/espace/payer-facture'
    | '/espace/profil'
    | '/espace/verifier-statut'
    | '/guichet/clients'
    | '/guichet/profil'
    | '/admin/'
    | '/espace/'
    | '/guichet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reinitialiser-mot-de-passe'
    | '/admin/agents'
    | '/admin/clients'
    | '/admin/guichets'
    | '/admin/profil'
    | '/espace/factures'
    | '/espace/payer-facture'
    | '/espace/profil'
    | '/espace/verifier-statut'
    | '/guichet/clients'
    | '/guichet/profil'
    | '/admin'
    | '/espace'
    | '/guichet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reinitialiser-mot-de-passe'
    | '/_authenticated/admin'
    | '/_authenticated/espace'
    | '/_authenticated/guichet'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/guichets'
    | '/_authenticated/admin/profil'
    | '/_authenticated/espace/factures'
    | '/_authenticated/espace/payer-facture'
    | '/_authenticated/espace/profil'
    | '/_authenticated/espace/verifier-statut'
    | '/_authenticated/guichet/clients'
    | '/_authenticated/guichet/profil'
    | '/_authenticated/admin/'
    | '/_authenticated/espace/'
    | '/_authenticated/guichet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guichet': {
      id: '/_authenticated/guichet'
      path: '/guichet'
      fullPath: '/guichet'
      preLoaderRoute: typeof AuthenticatedGuichetRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/guichets': {
      id: '/_authenticated/admin/guichets'
      path: '/guichets'
      fullPath: '/admin/guichets'
      preLoaderRoute: typeof AuthenticatedAdminGuichetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profil': {
      id: '/_authenticated/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AuthenticatedAdminProfilRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRouteRoute
    }
    '/_authenticated/espace/factures': {
      id: '/_authenticated/espace/factures'
      path: '/factures'
      fullPath: '/espace/factures'
      preLoaderRoute: typeof AuthenticatedEspaceFacturesRouteImport
      parentRoute: typeof AuthenticatedEspaceRouteRoute
    }
    '/_authenticated/espace/payer-facture': {
      id: '/_authenticated/espace/payer-facture'
      path: '/payer-facture'
      fullPath: '/espace/payer-facture'
      preLoaderRoute: typeof AuthenticatedEspacePayerFactureRouteImport
      parentRoute: typeof AuthenticatedEspaceRouteRoute
    }
    '/_authenticated/espace/profil': {
      id: '/_authenticated/espace/profil'
      path: '/profil'
      fullPath: '/espace/profil'
      preLoaderRoute: typeof AuthenticatedEspaceProfilRouteImport
      parentRoute: typeof AuthenticatedEspaceRouteRoute
    }
    '/_authenticated/espace/verifier-statut': {
      id: '/_authenticated/espace/verifier-statut'
      path: '/verifier-statut'
      fullPath: '/espace/verifier-statut'
      preLoaderRoute: typeof AuthenticatedEspaceVerifierStatutRouteImport
      parentRoute: typeof AuthenticatedEspaceRouteRoute
    }
    '/_authenticated/guichet/': {
      id: '/_authenticated/guichet/'
      path: '/'
      fullPath: '/guichet/'
      preLoaderRoute: typeof AuthenticatedGuichetIndexRouteImport
      parentRoute: typeof AuthenticatedGuichetRouteRoute
    }
    '/_authenticated/guichet/clients': {
      id: '/_authenticated/guichet/clients'
      path: '/clients'
      fullPath: '/guichet/clients'
      preLoaderRoute: typeof AuthenticatedGuichetClientsRouteImport
      parentRoute: typeof AuthenticatedGuichetRouteRoute
    }
    '/_authenticated/guichet/profil': {
      id: '/_authenticated/guichet/profil'
      path: '/profil'
      fullPath: '/guichet/profil'
      preLoaderRoute: typeof AuthenticatedGuichetProfilRouteImport
      parentRoute: typeof AuthenticatedGuichetRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminGuichetsRoute: typeof AuthenticatedAdminGuichetsRoute
  AuthenticatedAdminProfilRoute: typeof AuthenticatedAdminProfilRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
    AuthenticatedAdminGuichetsRoute: AuthenticatedAdminGuichetsRoute,
    AuthenticatedAdminProfilRoute: AuthenticatedAdminProfilRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEspaceRouteRouteChildren {
  AuthenticatedEspaceFacturesRoute: typeof AuthenticatedEspaceFacturesRoute
  AuthenticatedEspacePayerFactureRoute: typeof AuthenticatedEspacePayerFactureRoute
  AuthenticatedEspaceProfilRoute: typeof AuthenticatedEspaceProfilRoute
  AuthenticatedEspaceVerifierStatutRoute: typeof AuthenticatedEspaceVerifierStatutRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
}

const AuthenticatedEspaceRouteRouteChildren: AuthenticatedEspaceRouteRouteChildren =
  {
    AuthenticatedEspaceFacturesRoute: AuthenticatedEspaceFacturesRoute,
    AuthenticatedEspacePayerFactureRoute: AuthenticatedEspacePayerFactureRoute,
    AuthenticatedEspaceProfilRoute: AuthenticatedEspaceProfilRoute,
    AuthenticatedEspaceVerifierStatutRoute:
      AuthenticatedEspaceVerifierStatutRoute,
    AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
  }

const AuthenticatedEspaceRouteRouteWithChildren =
  AuthenticatedEspaceRouteRoute._addFileChildren(
    AuthenticatedEspaceRouteRouteChildren,
  )

interface AuthenticatedGuichetRouteRouteChildren {
  AuthenticatedGuichetClientsRoute: typeof AuthenticatedGuichetClientsRoute
  AuthenticatedGuichetProfilRoute: typeof AuthenticatedGuichetProfilRoute
  AuthenticatedGuichetIndexRoute: typeof AuthenticatedGuichetIndexRoute
}

const AuthenticatedGuichetRouteRouteChildren: AuthenticatedGuichetRouteRouteChildren =
  {
    AuthenticatedGuichetClientsRoute: AuthenticatedGuichetClientsRoute,
    AuthenticatedGuichetProfilRoute: AuthenticatedGuichetProfilRoute,
    AuthenticatedGuichetIndexRoute: AuthenticatedGuichetIndexRoute,
  }

const AuthenticatedGuichetRouteRouteWithChildren =
  AuthenticatedGuichetRouteRoute._addFileChildren(
    AuthenticatedGuichetRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEspaceRouteRoute: typeof AuthenticatedEspaceRouteRouteWithChildren
  AuthenticatedGuichetRouteRoute: typeof AuthenticatedGuichetRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEspaceRouteRoute: AuthenticatedEspaceRouteRouteWithChildren,
  AuthenticatedGuichetRouteRoute: AuthenticatedGuichetRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
